#!/usr/bin/env bash

# setup

rm -rf /tmp/tmsu/init_test
mkdir -p /tmp/tmsu/init_test

# test

tmsu init /tmp/tmsu/init_test    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# verify

if [[ ! -f /tmp/tmsu/init_test/.tmsu/db  ]]; then
    echo "database was not created"
    exit 1
fi
