#!/usr/bin/env bash

# setup

rm -rf /tmp/tmsu/init_test
mkdir -p /tmp/tmsu

# test

tmsu --database=/tmp/tmsu/init_test init   >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

if [[ ! -f /tmp/tmsu/init_test  ]]; then
    echo "database was not created"
    exit 1
fi
