#!/usr/bin/env bash

# setup

tmsu tag --tags="crocodile" --force '/tmp/tmsu/file:' '/tmp/tmsu/file\' '/tmp/tmsu/file\:'    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# test

tmsu tags '/tmp/tmsu/file:' '/tmp/tmsu/file\' '/tmp/tmsu/file\:'                              >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'crocodile'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/file\\:: crocodile
/tmp/tmsu/file\\\\: crocodile
/tmp/tmsu/file\\\\\\:: crocodile
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
