#!/usr/bin/env bash

# setup

touch /tmp/tmsu/file1
tmsu tag /tmp/tmsu/file1 aubergine      >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu imply aubergine vegetable          >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# test

tmsu tags --explicit /tmp/tmsu/file1    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
tmsu: new tag 'vegetable'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/file1: aubergine
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
