#!/usr/bin/env bash

# setup

touch /tmp/tmsu/file1 /tmp/tmsu/file2
tmsu tag /tmp/tmsu/file1 color=orange    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu tag /tmp/tmsu/file2 fruit=orange    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# test

tmsu tags --value orange                 >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'color'
tmsu: new value 'orange'
tmsu: new tag 'fruit'
tmsu: '/tmp/tmsu/file2' is a duplicate
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
orange: color fruit
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
