#!/usr/bin/env bash

# setup

echo 1 >/tmp/tmsu/file1
echo 2 >/tmp/tmsu/file2
tmsu tag --tags="aubergine" /tmp/tmsu/file1 /tmp/tmsu/file2    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# test

tmsu tags --count /tmp/tmsu/file1 /tmp/tmsu/file2              >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/file1: 1
/tmp/tmsu/file2: 1
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
