#!/usr/bin/env bash

# test

mkdir -p /tmp/tmsu/dir
echo 1 >/tmp/tmsu/dir/file1
tmsu tag --recursive /tmp/tmsu/dir aubergine              >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu tags --explicit /tmp/tmsu/dir /tmp/tmsu/dir/file1    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu untag /tmp/tmsu/dir aubergine                        >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tags --explicit /tmp/tmsu/dir /tmp/tmsu/dir/file1    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu untagged /tmp/tmsu/dir /tmp/tmsu/dir/file1           >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/dir: aubergine
/tmp/tmsu/dir/file1: aubergine
/tmp/tmsu/dir:
/tmp/tmsu/dir/file1: aubergine
/tmp/tmsu/dir
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
