#!/usr/bin/env bash

# setup

touch /tmp/tmsu/file1
tmsu tag /tmp/tmsu/file1 year=2015      >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# test

tmsu untag /tmp/tmsu/file1 year=2015    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

tmsu values                             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'year'
tmsu: new value '2015'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
2015
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
