#!/usr/bin/env bash

#TODO pipe to `sort` below should be unnecessary

# test

mkdir -p /tmp/tmsu/dir
echo 1 >/tmp/tmsu/dir/file1
echo 2 >/tmp/tmsu/dir/file2
tmsu tag --recursive /tmp/tmsu/dir aubergine              >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu tags --explicit /tmp/tmsu/dir /tmp/tmsu/dir/file1    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu untag --recursive /tmp/tmsu/dir aubergine            >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tags --explicit /tmp/tmsu/dir /tmp/tmsu/dir/file1    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu untagged /tmp/tmsu/dir | sort                        >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/dir: aubergine
/tmp/tmsu/dir/file1: aubergine
/tmp/tmsu/dir:
/tmp/tmsu/dir/file1:
/tmp/tmsu/dir
/tmp/tmsu/dir/file1
/tmp/tmsu/dir/file2
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
