#!/usr/bin/env bash

# test

touch /tmp/tmsu/file1
tmsu tag /tmp/tmsu/file1 aubergine      >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu tags --explicit /tmp/tmsu/file1    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu untag /tmp/tmsu/file1 aubergine    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tags --explicit /tmp/tmsu/file1    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu untagged /tmp/tmsu/file1           >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/file1: aubergine
/tmp/tmsu/file1:
/tmp/tmsu/file1
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
