#!/usr/bin/env bash

# test

echo 1 >/tmp/tmsu/file1
echo 2 >/tmp/tmsu/file2
tmsu tag --tags="aubergine potato" /tmp/tmsu/file1 /tmp/tmsu/file2    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu tags --explicit /tmp/tmsu/file1 /tmp/tmsu/file2                  >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu untag --all /tmp/tmsu/file1 /tmp/tmsu/file2                      >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tags --explicit /tmp/tmsu/file1 /tmp/tmsu/file2                  >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu untagged /tmp/tmsu/file1 /tmp/tmsu/file2                         >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
tmsu: new tag 'potato'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/file1: aubergine potato
/tmp/tmsu/file2: aubergine potato
/tmp/tmsu/file1:
/tmp/tmsu/file2:
/tmp/tmsu/file1
/tmp/tmsu/file2
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
