#!/usr/bin/env bash

# test

tmsu tag /tmp/tmsu/file1 year=2015 year=2016   >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu rename --value 2015 2016                  >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'year'
tmsu: new value '2015'
tmsu: new value '2016'
tmsu: value '2016' already exists
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - </dev/null
if [[ $? -ne 0 ]]; then
    exit 1
fi
