#!/usr/bin/env bash

# setup

touch /tmp/tmsu/file1
tmsu tag /tmp/tmsu/file1 year=2015    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# test

tmsu rename --value 2015 2016        >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'year'
tmsu: new value '2015'
tmsu: could not rename value '2015' to '2016': tag value cannot contain U+0002
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - </dev/null
if [[ $? -ne 0 ]]; then
    exit 1
fi
