#!/usr/bin/env bash

# test

tmsu tag --force /tmp/tmsu/somefile year=2015    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu rename --value 2015 2016                    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files year=2015                             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files year=2016                             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'year'
tmsu: new value '2015'
tmsu: no such value '2015'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/somefile
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
