#!/usr/bin/env bash

add_file() {
  id=$1
  path="$2"
  directory=$(dirname "$2")
  filename=$(basename "$2")

  sqlite3 $TMSU_DB <<EOF
INSERT INTO file (id, directory, name, fingerprint, mod_time, size, is_dir)
VALUES
    ($id, '$directory', '$filename', '', datetime(), 0, false);
EOF
}

add_tag() {
    id=$1
    name="$2"

    sqlite3 $TMSU_DB <<EOF
INSERT INTO tag (id, name)
VALUES ($id, '$name');
EOF
}

add_value() {
    id=$1
    name="$2"

    sqlite3 $TMSU_DB <<EOF
INSERT INTO value (id, name)
VALUES ($id, '$name');
EOF
}

add_file_tag() {
    file_id=$1
    tag_id=$2
    value_id=$3

    sqlite3 $TMSU_DB <<EOF
INSERT INTO file_tag (file_id, tag_id, value_id)
VALUES
    ($file_id, $tag_id, $value_id);
EOF
}

add_implication() {
	tag_id=$1
	value_id=$2
	implied_tag_id=$3
	implied_value_id=$4

	sqlite3 $TMSU_DB <<EOF
INSERT INTO implication (tag_id, value_id, implied_tag_id, implied_value_id)
VALUES
	($tag_id, $value_id, $implied_tag_id, $implied_value_id);
EOF
}
