#!/usr/bin/env bash

add_file() {
  local id=$1
  local path="$2"
  local mod_time="${3:-2025-01-01T00:00:00Z}"
  local size="${4:-0}"

  directory=$(dirname "$path")
  filename=$(basename "$path")

  sqlite3 $TMSU_DB <<EOF
INSERT INTO file (id, directory, name, fingerprint, mod_time, size, is_dir)
VALUES
    ($id, '$directory', '$filename', '', '$mod_time', $size, false);
EOF
}

add_dir() {
  local id=$1
  local path="$2"

  directory=$(dirname "$path")
  filename=$(basename "$path")

  sqlite3 $TMSU_DB <<EOF
INSERT INTO file (id, directory, name, fingerprint, mod_time, size, is_dir)
VALUES
    ($id, '$directory', '$filename', '', datetime(), 0, true);
EOF
}

add_tag() {
    local id=$1
    local name="$2"

    sqlite3 $TMSU_DB <<EOF
INSERT INTO tag (id, name)
VALUES ($id, '$name');
EOF
}

add_value() {
    local id=$1
    local name="$2"

    sqlite3 $TMSU_DB <<EOF
INSERT INTO value (id, name)
VALUES ($id, '$name');
EOF
}

add_file_tag() {
    local file_id=$1
    local tag_id=$2
    local value_id=$3

    sqlite3 $TMSU_DB <<EOF
INSERT INTO file_tag (file_id, tag_id, value_id)
VALUES
    ($file_id, $tag_id, $value_id);
EOF
}

add_implication() {
	local tag_id=$1
	local value_id=$2
	local implied_tag_id=$3
	local implied_value_id=$4

	sqlite3 $TMSU_DB <<EOF
INSERT INTO implication (tag_id, value_id, implied_tag_id, implied_value_id)
VALUES
	($tag_id, $value_id, $implied_tag_id, $implied_value_id);
EOF
}
