#!/usr/bin/env bash

if [[ -z $1 ]]; then
    echo "no testcase paths specified" >&2
    exit 1
fi

export TESTS_DIR=$(dirname $BASH_SOURCE[0])
export PATH=$TESTS_DIR/../bin:$PATH

failed=0

for testcase in $*; do
	if [[ "$testcase" =~ SKIP_ ]]; then
		continue
	fi

    . $TESTS_DIR/setup

    bash <<EOF
source db
source $testcase
EOF
    export RC=$?

	echo -n "$testcase"
    if [[ $RC -eq 0 ]]; then
        echo " [PASS]"

        $TESTS_DIR/teardown
    else
        echo " [FAIL]"
        failed=1
    fi
done

if (( $failed)); then
	exit 1
fi
