#!/usr/bin/env bash

if [[ -z $1 ]]; then
    echo "no testcase paths specified" >&2
    exit 1
fi

export PATH=$(dirname $_)/../bin:$PATH

for testcase in $*; do
    # clean slate
    rm -r /tmp/tmsu 2>/dev/null
    mkdir -p /tmp/tmsu

    # (re)create the database
    tmsu init /tmp/tmsu >/dev/null 2>/dev/null
    export TMSU_DB=/tmp/tmsu/.tmsu/db

    # run set-up
    ./setup

    # run the testcase
    ./$testcase
    export RC=$?

    # report result
    echo -n "$testcase "
    if [[ $RC -eq 0 ]]; then
        echo "[PASS]"
    else
        echo "[FAIL]"
        exit 1
    fi
done
