#!/usr/bin/env bash

if [[ -z $1 ]]; then
    echo "no testcase paths specified" >&2
    exit 1
fi

export TESTS_DIR=$(dirname $BASH_SOURCE[0])
export PATH=$TESTS_DIR/../bin:$PATH

for testcase in $*; do
    . $TESTS_DIR/setup

    $testcase
    export RC=$?

    echo -n "$testcase "
    if [[ $RC -eq 0 ]]; then
        echo "[PASS]"

        $TESTS_DIR/teardown
    else
        echo "[FAIL]"
        exit 1
    fi
done
