#!/usr/bin/env bash

if [[ -z $1 ]]; then
    files=$( find . -mindepth 2 -perm -+x )
else
    files=$( find $1 -mindepth 1 -perm -+x )
fi

export RC=0

for testcase in $files; do
    ./run $testcase
    export RC=$(( $RC + $? ))
done

exit $RC
