#!/usr/bin/env bash

export PATH=$PATH:../crates/cli/target/debug

# (re)create the test directory
rm -r /tmp/tmsu 2>/dev/null
mkdir -p /tmp/tmsu

# create the database
tmsu init /tmp/tmsu >/dev/null 2>/dev/null
export TMSU_DB=/tmp/tmsu/.tmsu/db
