#!/usr/bin/env bash

export PATH=$PATH:../target/debug

# (re)create the test directory
rm -r /tmp/tmsu 2>/dev/null
mkdir -p /tmp/tmsu

# create the database
tmsu init /tmp/tmsu/db >/dev/null 2>/dev/null
export TMSU_DB=/tmp/tmsu/db
