#!/usr/bin/env bash

# setup

touch /tmp/tmsu/file1

# test

tmsu tag /tmp/tmsu/file1 one\\=two     >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu tag /tmp/tmsu/file1 'two\=three'  >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tags /tmp/tmsu/file1              >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'one=two'
tmsu: new tag 'two=three'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/file1: one\=two two\=three
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
