#!/usr/bin/env bash

# setup

mkdir /tmp/tmsu/dir1
touch /tmp/tmsu/dir1/file1

# test

tmsu tag /tmp/tmsu/dir1 aubergine            >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu tags --explicit /tmp/tmsu/dir1          >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tags --explicit /tmp/tmsu/dir1/file1    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/dir1: aubergine
/tmp/tmsu/dir1/file1:
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
