#!/usr/bin/env bash

echo 1 >/tmp/tmsu/file1
echo 2 >/tmp/tmsu/file2

# test

tmsu tag /tmp/tmsu/file1 aubergine potato          >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu tag --from=/tmp/tmsu/file1 /tmp/tmsu/file2    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tags /tmp/tmsu/file1 /tmp/tmsu/file2          >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
tmsu: new tag 'potato'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/file1: aubergine potato
/tmp/tmsu/file2: aubergine potato
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
