#!/usr/bin/env bash

# test

tmsu tag /tmp/tmsu/file1 au/bergine    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu tags --explicit /tmp/tmsu/file1   >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: could not create tag 'au/bergine': tag names cannot contain '/'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/file1:
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
