#!/usr/bin/env bash

# test

tmsu tag --force --tags="aubergine potato" /some/file /other/file    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu tags --explicit /some/file /other/file                          >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr 

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
tmsu: new tag 'potato'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/some/file: aubergine potato
/other/file: aubergine potato
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
