#!/usr/bin/env bash

# test

tmsu tag --force /some/file aubergine potato      >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu tag --force --from=/some/file /other/file    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tags /other/file                             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
tmsu: new tag 'potato'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/other/file: aubergine potato
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
