#!/usr/bin/env bash

# setup

touch /tmp/tmsu/{file1,file2}

# test

tmsu tag --from=/tmp/tmsu/file1 /tmp/tmsu/file2    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: /tmp/tmsu/file1: path is not tagged
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
