#!/usr/bin/env bash

# test

tmsu imply aubergine vegetable                     >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu tag --force /some/file aubergine vegetable    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tags --explicit /some/file                    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tags /some/file                               >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
tmsu: new tag 'vegetable'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/some/file: aubergine
/some/file: aubergine vegetable
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
