#!/usr/bin/env bash

echo 1 >/tmp/tmsu/file1
echo 2 >/tmp/tmsu/file2
echo 3 >/tmp/tmsu/file3

# test

tmsu tag /tmp/tmsu/file1 aubergine                          >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu tag /tmp/tmsu/file2 potato                             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag /tmp/tmsu/file3 shiny-purple-veg                   >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag --where="aubergine or shiny-purple-veg" eggplant   >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tags /tmp/tmsu/file1 /tmp/tmsu/file2 /tmp/tmsu/file3   >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
tmsu: new tag 'potato'
tmsu: new tag 'shiny-purple-veg'
tmsu: new tag 'eggplant'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/file1: aubergine eggplant
/tmp/tmsu/file2: potato
/tmp/tmsu/file3: eggplant shiny-purple-veg
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
