#!/usr/bin/env bash

# test

tmsu tag --create aubergine potato "=2015" "=red"    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu tags                                            >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu values                                          >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
aubergine
potato
2015
red
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
