#!/usr/bin/env bash

# test

tmsu tag --create one=two        >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu tag --create 'two=three'    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tags                        >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
one\=two
two\=three
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
