#!/usr/bin/env bash

# test

tmsu tag --create au/bergine    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu tags --explicit            >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: could not create tag 'au/bergine': tag names cannot contain '/'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
