#!/usr/bin/env bash

# test

tmsu tag --create .              >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag --create ..             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag --create and            >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag --create or             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag --create not            >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag --create eq             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag --create ne             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag --create lt             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag --create gt             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag --create le             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag --create ge             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag --create AND            >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag --create OR             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag --create NOT            >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag --create EQ             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag --create NE             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag --create LT             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag --create GT             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag --create LE             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag --create GE             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tags --explicit             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: could not create tag '.': tag name cannot be '.' or '..'
tmsu: could not create tag '..': tag name cannot be '.' or '..'
tmsu: could not create tag 'and': tag name cannot be a logical operator: 'and', 'or' or 'not'
tmsu: could not create tag 'or': tag name cannot be a logical operator: 'and', 'or' or 'not'
tmsu: could not create tag 'not': tag name cannot be a logical operator: 'and', 'or' or 'not'
tmsu: could not create tag 'eq': tag name cannot be a comparison operator: 'eq', 'ne', 'gt', 'lt', 'ge' or 'le'
tmsu: could not create tag 'ne': tag name cannot be a comparison operator: 'eq', 'ne', 'gt', 'lt', 'ge' or 'le'
tmsu: could not create tag 'lt': tag name cannot be a comparison operator: 'eq', 'ne', 'gt', 'lt', 'ge' or 'le'
tmsu: could not create tag 'gt': tag name cannot be a comparison operator: 'eq', 'ne', 'gt', 'lt', 'ge' or 'le'
tmsu: could not create tag 'le': tag name cannot be a comparison operator: 'eq', 'ne', 'gt', 'lt', 'ge' or 'le'
tmsu: could not create tag 'ge': tag name cannot be a comparison operator: 'eq', 'ne', 'gt', 'lt', 'ge' or 'le'
tmsu: could not create tag 'AND': tag name cannot be a logical operator: 'and', 'or' or 'not'
tmsu: could not create tag 'OR': tag name cannot be a logical operator: 'and', 'or' or 'not'
tmsu: could not create tag 'NOT': tag name cannot be a logical operator: 'and', 'or' or 'not'
tmsu: could not create tag 'EQ': tag name cannot be a comparison operator: 'eq', 'ne', 'gt', 'lt', 'ge' or 'le'
tmsu: could not create tag 'NE': tag name cannot be a comparison operator: 'eq', 'ne', 'gt', 'lt', 'ge' or 'le'
tmsu: could not create tag 'LT': tag name cannot be a comparison operator: 'eq', 'ne', 'gt', 'lt', 'ge' or 'le'
tmsu: could not create tag 'GT': tag name cannot be a comparison operator: 'eq', 'ne', 'gt', 'lt', 'ge' or 'le'
tmsu: could not create tag 'LE': tag name cannot be a comparison operator: 'eq', 'ne', 'gt', 'lt', 'ge' or 'le'
tmsu: could not create tag 'GE': tag name cannot be a comparison operator: 'eq', 'ne', 'gt', 'lt', 'ge' or 'le'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
