#!/usr/bin/env bash

# test

tmsu tag --create "=aubergine"    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu values                       >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
aubergine
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
