#!/usr/bin/env bash

# test

tmsu tag --force /tmp/tmsu/noexist aubergine    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu tags /tmp/tmsu/noexist                     >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/noexist: aubergine
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
