#!/usr/bin/env bash

# test

tmsu info    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff -I "^Size" /tmp/tmsu/stdout - <<EOF
Database: /tmp/tmsu/.tmsu/db
Root path: /tmp/tmsu
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
