#!/usr/bin/env bash

# setup

touch /tmp/tmsu/file1
tmsu tag /tmp/tmsu/file1 aubergine=good    >/dev/null 2>&1

# test

tmsu info --stats                          >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff -I "^Size" /tmp/tmsu/stdout - <<EOF
Database: /tmp/tmsu/.tmsu/db
Root path: /tmp/tmsu

Tags: 1
Values: 1
Files: 1
Taggings: 1
Mean tags per file: 1.00
Mean files per tag: 1.00
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
