#!/usr/bin/env bash

# setup

touch /tmp/tmsu/file1
tmsu tag /tmp/tmsu/file1 aubergine=good    >/dev/null 2>&1

# test

tmsu info --usage                          >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff -I "^Size" /tmp/tmsu/stdout - <<EOF
Database: /tmp/tmsu/.tmsu/db
Root path: /tmp/tmsu

  aubergine 1
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
