#!/usr/bin/env bash

# setup

touch /tmp/tmsu/file1
tmsu tag /tmp/tmsu/file1 year=2015 country=Iceland    >/dev/null 2>&1

# test

tmsu delete --value 2015 Iceland                      >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# verify

tmsu values                                           >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

diff /tmp/tmsu/stderr - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
