#!/usr/bin/env bash

# setup

touch /tmp/tmsu/file1
tmsu tag /tmp/tmsu/file1 aubergine    >/dev/null 2>&1

# test

tmsu delete aubergine                 >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# verify

tmsu files aubergine                  >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

diff /tmp/tmsu/stderr - <<EOF
tmsu: no such tag 'aubergine'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
