#!/usr/bin/env bash

# setup

tmsu tag /tmp/tmsu/file1 aubergine    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# test

tmsu delete aubergine                 >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

tmsu files aubergine                  >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
tmsu: no such tag 'aubergine'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
