#!/usr/bin/env bash

# test

tmsu tag --create aubergine eggplant    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu delete aubergine eggplant          >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files aubergine                    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files eggplant                     >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: no such tag 'aubergine'
tmsu: no such tag 'eggplant'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
