#!/usr/bin/env bash

# setup

tmsu tag /tmp/tmsu/file1 aubergine eggplant    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# test

tmsu delete aubergine eggplant                 >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

tmsu files aubergine                           >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files eggplant                            >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
tmsu: new tag 'eggplant'
tmsu: no such tag 'aubergine'
tmsu: no such tag 'eggplant'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
