#!/usr/bin/env bash

# test

tmsu tag --force /tmp/tmsu/somefile year=2015 country=Iceland >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu delete --value 2015 Iceland >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files year=2015 >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files country=Iceland >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stdout - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'year'
tmsu: new value '2015'
tmsu: new tag 'country'
tmsu: new value 'Iceland'
tmsu: no such value '2015'
tmsu: no such value 'Iceland'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
