#!/usr/bin/env bash

# setup

touch /tmp/tmsu/file1
tmsu tag /tmp/tmsu/file1 vegetable=brocolli year=2015 year=2016    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# test

tmsu values --count year                                           >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'vegetable'
tmsu: new value 'brocolli'
tmsu: new tag 'year'
tmsu: new value '2015'
tmsu: new value '2016'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
2
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
