#!/usr/bin/env bash

#TODO ideally this case would be handled explicitly with more specific error message (like 'merge a a')

# test

tmsu tag /tmp/tmsu/file1 aubergine    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu copy aubergine aubergine         >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tags                             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
tmsu: a tag with name 'aubergine' already exists
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
aubergine
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
