#!/usr/bin/env bash

# setup

touch /tmp/tmsu/file1
tmsu tag /tmp/tmsu/file1 aubergine eggplant    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# test

tmsu copy aubergine eggplant                   >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

tmsu tags /tmp/tmsu/file1                      >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
tmsu: new tag 'eggplant'
tmsu: a tag with name 'eggplant' already exists
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/file1: aubergine eggplant
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
