#!/usr/bin/env bash

# test

tmsu copy aubergine eggplant    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stdout - </dev/null
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stderr - <<EOF
tmsu: no such tag 'aubergine'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
