#!/usr/bin/env bash

# setup

echo dupe >/tmp/tmsu/file1
cp /tmp/tmsu/file1 /tmp/tmsu/file2
mkdir -p /tmp/tmsu/dir
cp /tmp/tmsu/file1 /tmp/tmsu/dir/file3
tmsu tag --tags="aubergine" /tmp/tmsu/file1 /tmp/tmsu/file2    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu tag --recursive /tmp/tmsu/dir/file3 aubergine             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# test

tmsu dupes                                                     >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
tmsu: '/tmp/tmsu/file2' is a duplicate
tmsu: '/tmp/tmsu/dir/file3' is a duplicate
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
Set of 3 duplicates:
  /tmp/tmsu/file1
  /tmp/tmsu/file2
  /tmp/tmsu/dir/file3
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
