#!/usr/bin/env bash

# setup

tmsu tag --tags="aubergine" /tmp/tmsu/file1 /tmp/tmsu/file3dupe1    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu tag --recursive /tmp/tmsu/dir1 aubergine                       >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# test

tmsu dupes                                                          >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
tmsu: '/tmp/tmsu/file3dupe1' is a duplicate
tmsu: '/tmp/tmsu/dir1/file1' is a duplicate
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
Set of 3 duplicates:
  /tmp/tmsu/file1
  /tmp/tmsu/file3dupe1
  /tmp/tmsu/dir1/file1
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
