#!/usr/bin/env bash

# setup

echo dupe >/tmp/tmsu/file1
mkdir -p /tmp/tmsu/dir
cp /tmp/tmsu/file1 /tmp/tmsu/dir/file2
tmsu tag --tags="aubergine" /tmp/tmsu/file1    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# test

tmsu dupes --recursive /tmp/tmsu/dir           >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/dir/file2:
  /tmp/tmsu/file1
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
