#!/usr/bin/env bash

# setup

mkdir /tmp/tmsu/dir
touch /tmp/tmsu/dir/{file1,file2,file3}
tmsu tag /tmp/tmsu/dir aubergine          >/dev/null 2>&1
tmsu tag /tmp/tmsu/dir/file1 aubergine    >/dev/null 2>&1

# test

tmsu untagged --count /tmp/tmsu/dir       >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
2
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
