#!/usr/bin/env bash

# setup

mkdir /tmp/tmsu/dir
touch /tmp/tmsu/dir/file1
touch /tmp/tmsu/dir/file2
touch /tmp/tmsu/dir/file3
tmsu tag /tmp/tmsu/dir/file1 aubergine    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# test

tmsu untagged /tmp/tmsu/dir | sort        >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/dir
/tmp/tmsu/dir/file2
/tmp/tmsu/dir/file3
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
