include $(GOROOT)/src/Make.inc

TARG=tmsu
GOFILES=config.go \
		main.go \
		command.go \
		commands/help.go \
		commands/mount.go \
		commands/unmount.go \
		commands/add.go \
		commands/remove.go \
		commands/tags.go \
		commands/tag.go \
		commands/untag.go \
		commands/rename.go \
		commands/merge.go \
		database.go \
		fusefs.go \
		tag.go \
		file.go \
		filepath.go \
		filetag.go \
		fingerprinter.go

include $(GOROOT)/src/Make.cmd
