#!/usr/bin/env bash

# test

tmsu config autoCreateTags=no fileFingerprintAlgorithm=none    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu config autoCreateTags fileFingerprintAlgorithm            >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - </dev/null
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
autoCreateTags=no
fileFingerprintAlgorithm=none
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
