#!/usr/bin/env bash

# test

tmsu config    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - </dev/null
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
autoCreateTags=yes
autoCreateValues=yes
directoryFingerprintAlgorithm=none
fileFingerprintAlgorithm=dynamic:SHA256
reportDuplicates=yes
symlinkFingerprintAlgorithm=follow
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
