#!/usr/bin/env bash

# test

tmsu config directoryFingerprintAlgorithm autoCreateTags    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - </dev/null
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
directoryFingerprintAlgorithm=none
autoCreateTags=yes
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
