include $(GOROOT)/src/Make.inc

TARG=tmsu
GOFILES=config.go \
		main.go \
		version.go \
		command.go \
		commands/help.go \
		commands/mount.go \
		commands/unmount.go \
		commands/tags.go \
		commands/tag.go \
		commands/untag.go \
		commands/rename.go \
		commands/merge.go \
		commands/delete.go \
		commands/export.go \
		commands/vfs.go \
		commands/status.go \
		commands/version.go \
		entities/tag.go \
		entities/file.go \
		entities/filetag.go \
		database.go \
		fusevfs.go \
		fingerprinter.go

include $(GOROOT)/src/Make.cmd
