#!/usr/bin/env bash

# test

tmsu imply aubergine vegetable    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu imply vegetable food         >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

tmsu imply                        >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
tmsu: new tag 'vegetable'
tmsu: new tag 'food'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
aubergine -> vegetable
vegetable -> food
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
