#!/usr/bin/env bash

# test

tmsu imply MMXV year=2015    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu imply year MMXV         >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'MMXV'
tmsu: new tag 'year'
tmsu: new value '2015'
tmsu: cannot add implication of 'year' to 'MMXV': implication would create a cycle
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
