#!/usr/bin/env bash

# test

tmsu imply aubergine vegetable    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu imply vegetable aubergine    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
tmsu: new tag 'vegetable'
tmsu: cannot add implication of 'vegetable' to 'aubergine': implication would create a cycle
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
