#!/usr/bin/env bash

# test

tmsu imply aubergine food=vegetable         >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu imply food=vegetable song=plantlife    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

tmsu imply                             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
tmsu: new tag 'food'
tmsu: new value 'vegetable'
tmsu: new tag 'song'
tmsu: new value 'plantlife'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
     aubergine -> food=vegetable
food=vegetable -> song=plantlife
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
