#!/usr/bin/env bash

# test

tmsu imply year=2015 MMXV    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu imply MMXV year=2015    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'year'
tmsu: new value '2015'
tmsu: new tag 'MMXV'
tmsu: cannot add implication of 'MMXV' to 'year=2015': implication would create a cycle
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
