#!/usr/bin/env bash

# setup

tmsu imply food=aubergine class=vegetable             >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu imply                                            >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr  

# test

tmsu imply --delete food=aubergine class=vegetable    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr  

# verify

tmsu imply                                      >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr  

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'food'
tmsu: new value 'aubergine'
tmsu: new tag 'class'
tmsu: new value 'vegetable'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
food=aubergine -> class=vegetable
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
