#!/usr/bin/env bash

# setup

touch /tmp/tmsu/{file1,file2}
tmsu tag /tmp/tmsu/file1 aubergine    >/dev/null 2>&1
tmsu tag /tmp/tmsu/file2 potato       >/dev/null 2>&1

# test

tmsu files --count aubergine          >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
1
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
