#!/usr/bin/env bash

# setup

add_file 1 '/file1'
add_file 2 '/file2'
add_tag 1 'aubergine'
add_tag 2 'potato'
add_file_tag 1 1 0
add_file_tag 2 2 0

# test

tmsu files --count aubergine          >>$OUT 2>>$ERR

# verify

diff - <<EOF $ERR
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff - <<EOF $OUT
1
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
