#!/usr/bin/env bash

# setup

touch /tmp/tmsu/{file1,file2}
mkdir /tmp/tmsu/dir1
tmsu tag --tags="aubergine" /tmp/tmsu/{file1,dir1}    >/dev/null 2>&1

# test

tmsu files --directory aubergine                      >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/dir1
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
