#!/usr/bin/env bash

# setup

add_file 1 '/file1'
add_dir 2 '/dir1'
add_tag 1 'aubergine'
add_file_tag 1 1 0
add_file_tag 2 1 0

# test

tmsu files --directory aubergine        >>$OUT 2>>$ERR

# verify

diff - <<EOF $ERR
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff - <<EOF $OUT
/dir1
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
