#!/usr/bin/env bash

# setup

tmsu tag /tmp/tmsu/file1 '<\=([!$%&!])\=>'            >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# test

tmsu files \\\<\\=\\\(\[\\\!\$%\&\\\!\]\\\)\\=\\\>    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files '\<\=\([\!$%&\!]\)\=\>'                    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag '<=([!$%&!])=>'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/file1
/tmp/tmsu/file1
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
