#!/usr/bin/env bash

# test

tmsu tag --tags="aubergine" /tmp/tmsu/file1 /tmp/tmsu/file2   >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu tag --tags="potato" /tmp/tmsu/file2                      >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files aubergine and potato                               >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files aubergine and not potato                           >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
tmsu: new tag 'potato'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/file2
/tmp/tmsu/file1
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
