#!/usr/bin/env bash

# setup

touch /tmp/tmsu/file1
mkdir /tmp/tmsu/dir1
tmsu tag --tags="aubergine" /tmp/tmsu/file1 /tmp/tmsu/dir1    >/dev/null 2>&1

# test

tmsu files --file aubergine                                   >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/file1
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
