#!/usr/bin/env bash

# setup

touch /tmp/tmsu/{file1,file2}
tmsu tag --tags="year=2015" /tmp/tmsu/file1    >/dev/null 2>&1
tmsu tag --tags="year=2016" /tmp/tmsu/file2    >/dev/null 2>&1

# test

tmsu files "year < 2016"                       >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/file1
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
