#!/usr/bin/env bash

# setup

touch /tmp/tmsu/{file1,file2,file3,file4}
tmsu tag --tags="month=June" /tmp/tmsu/file1               >/dev/null 2>&1
tmsu tag --tags="month=July" /tmp/tmsu/file2               >/dev/null 2>&1
tmsu tag --tags="blah" /tmp/tmsu/file3                     >/dev/null 2>&1
tmsu tag --tags="month=June month=July" /tmp/tmsu/file4    >/dev/null 2>&1

# test

tmsu files "month != June"                                 >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/file2
/tmp/tmsu/file3
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
