#!/usr/bin/env bash

# setup

touch /tmp/tmsu/{file1,file2,file3}

tmsu imply a b                          >/dev/null 2>&1
tmsu imply b c                          >/dev/null 2>&1
tmsu imply j=1 k                        >/dev/null 2>&1
tmsu imply k l                          >/dev/null 2>&1
tmsu imply x y=2                        >/dev/null 2>&1
tmsu imply y z                          >/dev/null 2>&1

tmsu tag /tmp/tmsu/file1 a              >/dev/null 2>&1
tmsu tag /tmp/tmsu/file2 j=1            >/dev/null 2>&1
tmsu tag /tmp/tmsu/file3 x              >/dev/null 2>&1

# test

tmsu files a                            >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu files b                            >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files c                            >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files a b c                        >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

tmsu files j=1                          >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files k                            >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files l                            >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files j=1 k l                      >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

tmsu files x                            >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files y=2                          >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files z                            >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files x y=2 z                      >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

tmsu tags /tmp/tmsu/file1               >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tags --explicit /tmp/tmsu/file1    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tags /tmp/tmsu/file2               >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tags --explicit /tmp/tmsu/file2    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tags /tmp/tmsu/file3               >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tags --explicit /tmp/tmsu/file3    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/file1
/tmp/tmsu/file1
/tmp/tmsu/file1
/tmp/tmsu/file1
/tmp/tmsu/file2
/tmp/tmsu/file2
/tmp/tmsu/file2
/tmp/tmsu/file2
/tmp/tmsu/file3
/tmp/tmsu/file3
/tmp/tmsu/file3
/tmp/tmsu/file3
/tmp/tmsu/file1: a b c
/tmp/tmsu/file1: a
/tmp/tmsu/file2: j=1 k l
/tmp/tmsu/file2: j=1
/tmp/tmsu/file3: x y=2 z
/tmp/tmsu/file3: x
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
