#!/usr/bin/env bash

# setup

tmsu imply a b                        >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu imply b c                        >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu imply j=1 k                      >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu imply k l                        >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu imply x y=2                      >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu imply y z                        >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

tmsu tag /tmp/tmsu/file1 a            >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag /tmp/tmsu/file2 j=1          >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag /tmp/tmsu/file4 x            >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# test

tmsu files a                          >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files b                          >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files c                          >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files a b c                      >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

tmsu files j=1                        >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files k                          >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files l                          >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files j=1 k l                    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

tmsu files x                          >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files y=2                        >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files z                          >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files x y=2 z                    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'a'
tmsu: new tag 'b'
tmsu: new tag 'c'
tmsu: new tag 'j'
tmsu: new value '1'
tmsu: new tag 'k'
tmsu: new tag 'l'
tmsu: new tag 'x'
tmsu: new tag 'y'
tmsu: new value '2'
tmsu: new tag 'z'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/file1
/tmp/tmsu/file1
/tmp/tmsu/file1
/tmp/tmsu/file1
/tmp/tmsu/file2
/tmp/tmsu/file2
/tmp/tmsu/file2
/tmp/tmsu/file2
/tmp/tmsu/file4
/tmp/tmsu/file4
/tmp/tmsu/file4
/tmp/tmsu/file4
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
