#!/usr/bin/env bash

# setup

add_file 1 '/file1'
add_file 2 '/file2'
add_file 3 '/file3'
add_file 4 '/file4'
add_tag 1 'a'
add_tag 2 'b'
add_tag 3 'c'
add_implication 1 0 2 0 # a -> b
add_implication 2 0 3 0 # b -> c
add_file_tag 1 1 0 		# /file1 a (b c)
add_file_tag 2 2 0 		# /file2 b (c)
add_file_tag 3 3 0 		# /file3 c

# test

echo -1-                                >>/tmp/tmsu/stdout
tmsu files a                            >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
echo -2-                                >>/tmp/tmsu/stdout
tmsu files b                            >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
echo -3-                                >>/tmp/tmsu/stdout
tmsu files c                            >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
echo -4-                                >>/tmp/tmsu/stdout
tmsu files a b c                        >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
echo -5-                                >>/tmp/tmsu/stdout
tmsu files b c                          >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
echo -6-                                >>/tmp/tmsu/stdout
tmsu files --explicit a                 >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
echo -7-                                >>/tmp/tmsu/stdout
tmsu files --explicit b                 >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
echo -8-                                >>/tmp/tmsu/stdout
tmsu files --explicit c                 >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff - <<EOF /tmp/tmsu/stderr
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff - <<EOF /tmp/tmsu/stdout
-1-
/file1
-2-
/file1
/file2
-3-
/file1
/file2
/file3
-4-
/file1
-5-
/file1
/file2
-6-
/file1
-7-
/file2
-8-
/file3
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
