#!/usr/bin/env bash

# setup

add_file 1 '/file1'
add_file 2 '/file2'
add_file 3 '/file3'
add_file 4 '/file4'
add_tag 1 'a'
add_tag 2 'b'
add_tag 3 'c'
add_implication 1 0 2 0 # a -> b
add_implication 2 0 3 0 # b -> c
add_file_tag 1 1 0 		# /file1 a (b c)
add_file_tag 2 2 0 		# /file2 b (c)
add_file_tag 3 3 0 		# /file3 c

# test

echo -1-                                >>$OUT
tmsu files a                            >>$OUT 2>>$ERR
echo -2-                                >>$OUT
tmsu files b                            >>$OUT 2>>$ERR
echo -3-                                >>$OUT
tmsu files c                            >>$OUT 2>>$ERR
echo -4-                                >>$OUT
tmsu files a b c                        >>$OUT 2>>$ERR
echo -5-                                >>$OUT
tmsu files b c                          >>$OUT 2>>$ERR
echo -6-                                >>$OUT
tmsu files --explicit a                 >>$OUT 2>>$ERR
echo -7-                                >>$OUT
tmsu files --explicit b                 >>$OUT 2>>$ERR
echo -8-                                >>$OUT
tmsu files --explicit c                 >>$OUT 2>>$ERR

# verify

diff - <<EOF $ERR
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff - <<EOF $OUT
-1-
/file1
-2-
/file1
/file2
-3-
/file1
/file2
/file3
-4-
/file1
-5-
/file1
/file2
-6-
/file1
-7-
/file2
-8-
/file3
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
