#!/usr/bin/env bash

# setup

tmsu tag --tags="aubergine" /tmp/tmsu/file1 /tmp/tmsu/dir1/file1    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# test

tmsu files --path="/tmp/tmsu/dir1" aubergine                        >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
tmsu: '/tmp/tmsu/dir1/file1' is a duplicate
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/dir1/file1
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
