#!/usr/bin/env bash

# setup

add_file 1 '/file1'
add_tag 1 '<==([!$%&!])==>'
add_file_tag 1 1 0

# test

tmsu files '"<==([!$%&!])==>"'                >>$OUT 2>>$ERR
tmsu files '\<\=\=\([\!$%&\!]\)\=\=\>'        >>$OUT 2>>$ERR

# verify

diff - <<EOF $ERR
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff - <<EOF $OUT
/file1
/file1
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
