#!/usr/bin/env bash

# test

tmsu imply aubergine vegetable        >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu tag /tmp/tmsu/file1 aubergine    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag /tmp/tmsu/file2 vegetable    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files vegetable                  >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
tmsu: new tag 'vegetable'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/file1
/tmp/tmsu/file2
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
