#!/usr/bin/env bash

# setup

tmsu tag /tmp/tmsu/file1 aubergine    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu tag /tmp/tmsu/file2 potato       >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# test

tmsu files aubergine                  >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
tmsu: new tag 'potato'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/file1
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
