#!/usr/bin/env bash

# setup

add_file 1 '/file1'
add_file 2 '/file2'
add_tag 1 'aubergine'
add_tag 2 'potato'
add_file_tag 1 1 0
add_file_tag 1 2 0
add_file_tag 2 2 0

# test

tmsu files potato aubergine                 >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# verify

diff - <<EOF /tmp/tmsu/stderr
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff - <<EOF /tmp/tmsu/stdout
/file1
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
