#!/usr/bin/env bash

# setup

mkdir /tmp/tmsu/dir1
touch /tmp/tmsu/{file1,dir1/file1}

tmsu tag --tags="aubergine" /tmp/tmsu/file1 /tmp/tmsu/dir1/file1    >/dev/null 2>&1

# test

tmsu files --path="/tmp/tmsu/dir1" aubergine                        >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# verify

diff - <<EOF /tmp/tmsu/stderr
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff - <<EOF /tmp/tmsu/stdout
/tmp/tmsu/dir1/file1
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
