#!/usr/bin/env bash

# setup

tmsu tag /tmp/tmsu/file1 vegetable=aubergine    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# test

tmsu merge --value potato aubergine             >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'vegetable'
tmsu: new value 'aubergine'
tmsu: no such value 'potato'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
