#!/usr/bin/env bash

# setup

touch /tmp/tmsu/file1

tmsu tag /tmp/tmsu/file1 vegetable=aubergine vegetable=potato    >/dev/null 2>&1

# test

tmsu merge --value aubergine brocolli potato                     >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# verify

tmsu values                                                      >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

diff /tmp/tmsu/stderr - <<EOF
tmsu: no such value 'brocolli'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
potato
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
