#!/usr/bin/env bash

# setup

mkdir /tmp/tmsu/dir1
touch /tmp/tmsu/{file1,file2,dir1/file1}

tmsu tag /tmp/tmsu/file1 aubergine       >/dev/null 2>&1
tmsu tag /tmp/tmsu/file2 potato          >/dev/null 2>&1
tmsu tag /tmp/tmsu/dir1/file1 brocolli   >/dev/null 2>&1

# test

tmsu merge aubergine potato brocolli     >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# verify

tmsu tags                                >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files brocolli                      >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

diff /tmp/tmsu/stderr - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
brocolli
/tmp/tmsu/file1
/tmp/tmsu/file2
/tmp/tmsu/dir1/file1
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
