#!/usr/bin/env bash

# setup

mkdir /tmp/tmsu/dir1
touch /tmp/tmsu/{file1,file2,dir1/file1}

tmsu tag /tmp/tmsu/file1 vegetable=aubergine        >/dev/null 2>&1
tmsu tag /tmp/tmsu/file2 vegetable=potato           >/dev/null 2>&1
tmsu tag /tmp/tmsu/dir1/file1 vegetable=brocolli    >/dev/null 2>&1

# test

tmsu merge --value aubergine potato brocolli        >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# verify

tmsu values                                         >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files vegetable=brocolli                       >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

diff /tmp/tmsu/stderr - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
brocolli
/tmp/tmsu/file1
/tmp/tmsu/file2
/tmp/tmsu/dir1/file1
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
