#!/usr/bin/env bash

# setup

touch /tmp/tmsu/{file1,file2}
tmsu tag /tmp/tmsu/file1 vegetable=aubergine    >/dev/null 2>&1
tmsu tag /tmp/tmsu/file2 vegetable=potato       >/dev/null 2>&1

# test

tmsu merge --value aubergine potato             >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr

# verify

tmsu values                                     >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu files vegetable=potato                     >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

diff /tmp/tmsu/stderr - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
potato
/tmp/tmsu/file1
/tmp/tmsu/file2
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
