EXP   = OR_EXP
OR_EXP  = AND_EXP | AND_EXP 'or' AND_EXP
AND_EXP = NOT_EXP | NOT_EXP 'and' NOT_EXP
NOT_EXP = EQUALS_EXP | 'not' NOT_EXP | ( EXP )
COMP_EXP = TAG_EXP | TAG_EXP = VALUE_EXP |
           TAG_EXP < VALUE_EXP | TAG_EXP > VALUE_EXP |
           TAG_EXP <= VALUE_EXP | TAG_EXP >= VALUE_EXP
