#!/usr/bin/env bash

# setup

mkdir -p /tmp/tmsu/dir
echo 1 >/tmp/tmsu/file1
echo 2 >/tmp/tmsu/file2
echo 3 >/tmp/tmsu/file3
echo 4 >/tmp/tmsu/dir/file4
touch /tmp/tmsu/file1 /tmp/tmsu/file2 /tmp/tmsu/file3 /tmp/tmsu/dir/file4
tmsu tag /tmp/tmsu/file1 aubergine    >|/tmp/tmsu/stdout 2>|/tmp/tmsu/stderr
tmsu tag /tmp/tmsu/file2 aubergine    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag /tmp/tmsu/file3 aubergine    >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
tmsu tag /tmp/tmsu/dir aubergine     >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr
rm /tmp/tmsu/file2
echo changed >>/tmp/tmsu/file3

# test

tmsu status                           >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
tmsu: new tag 'aubergine'
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
T /tmp/tmsu/dir
T /tmp/tmsu/file1
M /tmp/tmsu/file3
! /tmp/tmsu/file2
U /tmp/tmsu/dir/file4
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
