name: Build

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        run: cargo build --verbose

      - name: Unit tests
        run: cargo test

      - name: Integration tests
        working-directory: tests
        run: ./runall

